version: '3.9'
services:
  app:
    restart: always
    image: ${IMAGE_TAG}
    environment:
      DB_HOST: db
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_AUTHORIZED_USER_IDS: ${TELEGRAM_AUTHORIZED_USER_IDS}
    depends_on:
      - db
  db:
    restart: always
    image: postgres:15-alpine
    volumes:
      - ./test/db/postgres-init:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app

volumes:
  data: